[pytest]
minversion = 6.0
addopts = -ra -q
testpaths = tests
python_files = test_*.py
pythonpath = src
filterwarnings =
    ignore:Please use log_group_name instead of log_group:DeprecationWarning
    ignore:Please use log_stream_name instead of stream_name:DeprecationWarning
